FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster
RUN mkdir /root/.dotnet/tools
ENV PATH="/root/.dotnet/tools:${PATH}"
RUN  dotnet tool install dotnet-counters --global
WORKDIR /diagnostics
ENTRYPOINT [ "/usr/bin/dotnet", "counters" ]
