version: "3.7"
services:
  app:
    image: docker.pkg.github.com/phoenix-chen-2016/netcoremonitorexample/sampleweb:latest
    volumes:
      - dotnetdiag:/tmp:rw
  diag:
    image: webmonitor
    volumes:
      - dotnetdiag:/tmp:rw
    ports:
      - 8088:80
    pid: service:app
volumes:
  dotnetdiag:
